---
title: "hw-03-Aummul-Manasawala"
author: "Aummul Baneen Manasawala"
date: "March 21, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = "images/")
```

### Q 2.1

```{bash}
cut -d "," -f 2 nba2017-roster.csv | tail +2 | sort -u > team-names.txt
head -5 team-names.txt
```

### Q 2.2

```{bash}
cut -d "," -f 3 nba2017-roster.csv | tail +2 | sort -u > position-names.txt
head -5 position-names.txt
```

### Q 2.3

```{bash}
cut -d "," -f 7 nba2017-roster.csv | tail +2 | sort | uniq -c | sort -r > experience-counts.txt
head -5 experience-counts.txt
```

### Q 2.4
```{bash}
grep -E 'LAC|team' nba2017-roster.csv > LAC.csv
cat LAC.csv
```
### Q 2.5
```{bash}
grep "LAL" nba2017-roster.csv | cut -d "," -f 6 | sort | uniq -c
```
### Q 2.6
```{bash}
grep -c "CLE" nba2017-roster.csv
```
### Q 2.7
```{bash}
grep -E "GSW|team" nba2017-roster.csv | cut -d "," -f 1,4,5 > gsw-height-weight.csv
cat gsw-height-weight.csv
```


### Q 2.8
```{bash}
cut -d "," -f 1,8 nba2017-roster.csv | head -n 1 > top10-salaries.csv
cut -d "," -f 1,8 nba2017-roster.csv | tail +2| sort -n -t "," -k 2 -r|head -10 >> top10-salaries.csv
cat top10-salaries.csv
```

## Using the binomial-functions

```{r}
source("code/binomial-functions.R", local = F)
bin_probability(trials = 10, success = 3, prob = (1/6))
```

```{r distribution of probability of number of sixes in 10 trials}
dist_six <- bin_distribution(trials = 10, prob = 0.25)
dist_six
plot(dist_six, xlab = "number of sixes in 10 trials", ylab = "probability", main = "Distribution of probability of no of six in 10 trials")

```
```{r}
#Getting more than 3 heads in 5 tosses, p = 0.35
prob_more_than_three <- 0
for (i in 4:5) {
  prob_more_than_three <- prob_more_than_three + bin_probability(trials = 5, success = i, prob = 0.35)
}
prob_more_than_three
```

```{r distribution of probability of number of heads in 15 trials}

dist_heads <- bin_distribution(trials = 15, prob = 0.35)
dist_heads
plot(dist_heads, xlab = "number of heads in 15 trials", ylab = "probability", main = "Distribution of probability of no of heads in 15 trials")
```

